# Generated by Django 2.1.2 on 2018-11-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
