# Generated by Django 2.1.2 on 2018-10-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181028_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='guests',
            new_name='attendees',
        ),
    ]
