# Generated by Django 2.1.2 on 2018-10-19 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181018_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='reg_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
